site_name: BRF Glasera
theme:
  name: material
  language: sv
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - content.code.copy
markdown_extensions:
  - attr_list
plugins:
  - search
  - git-revision-date-localized
  - offline
extra:
  generator: false