site_name: BRF Glasera
theme:
  name: material
  language: sv
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - search.suggest
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - offline
  - awesome-pages
extra:
  generator: false
